# Generated by Django 4.2.2 on 2023-06-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='ShowTime',
        ),
    ]
