# Generated by Django 4.2.2 on 2023-06-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
