# Generated by Django 4.2.2 on 2023-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_date_showtime_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.ManyToManyField(blank=True, null=True, to='cinema.date'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='showtime',
            field=models.ManyToManyField(blank=True, null=True, to='cinema.showtime'),
        ),
    ]
