# Generated by Django 4.2.2 on 2023-06-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_seat_date_alter_seat_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='day',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='night',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='showtime',
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=True)),
                ('day', models.BooleanField(default=True)),
                ('night', models.BooleanField(default=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.date')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment', models.CharField()),
                ('seat', models.ManyToManyField(to='cinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
