# Generated by Django 4.2.2 on 2023-06-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_remove_seat_date_remove_seat_day_remove_seat_morning_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
