# Generated by Django 4.2.2 on 2023-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('pending', 'pending'), ('reserved', 'reserved')], max_length=100, null=True),
        ),
    ]
