# Generated by Django 4.2.2 on 2023-06-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_movie_active_seat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatavailability',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
    ]
