# Generated by Django 4.2.2 on 2023-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_seatavailability_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatavailability',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=(('available', 'available'), ('pending', 'pending'), ('reserved', 'reserved'))),
        ),
    ]
