# Generated by Django 4.2.2 on 2023-06-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('pending', 'pending'), ('reserved', 'reserved')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('pending', 'pending'), ('reserved', 'reserved')], max_length=20, null=True)),
                ('morning', models.BooleanField(default=True)),
                ('day', models.BooleanField(default=True)),
                ('night', models.BooleanField(default=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.date')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showtime')),
            ],
        ),
    ]
