# Generated by Django 4.2.2 on 2023-06-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatavailability',
            options={'ordering': ('movie',)},
        ),
        migrations.RemoveField(
            model_name='seatavailability',
            name='date',
        ),
    ]
