# Generated by Django 4.2.2 on 2023-06-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_date_showtime_movie_date'),
        ('booking', '0002_alter_seatavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatavailability',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.moviedate'),
        ),
    ]
