# Generated by Django 4.2.2 on 2023-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seat_screen_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='seats',
            field=models.ManyToManyField(related_name='seats', to='booking.seat'),
        ),
    ]
