# Generated by Django 4.2.2 on 2023-06-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_date_showtime_movie_date'),
        ('booking', '0003_seatavailability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='movie_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.moviedate'),
        ),
    ]
