# Generated by Django 4.2.2 on 2023-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookinghistory_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
