# Generated by Django 4.2.2 on 2023-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookinghistory_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seatavailability',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
