# Generated by Django 4.2.2 on 2023-06-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('active', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('showing', 'showing'), ('comingsoon', 'comingsoon')], max_length=100)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.CharField(choices=[('M', 'M'), ('D', 'D'), ('N', 'N')], max_length=10)),
                ('price', models.PositiveBigIntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.date')),
            ],
        ),
    ]
