# Generated by Django 4.2.2 on 2023-06-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('active', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('showing', 'showing'), ('comingsoon', 'comingsoon')], max_length=100)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Night', 'Night')], max_length=10)),
                ('price', models.PositiveBigIntegerField()),
                ('cinema_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('show_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showdate')),
            ],
        ),
    ]
