# Generated by Django 4.2.2 on 2023-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
