# Generated by Django 4.2.2 on 2023-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='date',
        ),
    ]
