# Generated by Django 4.2.2 on 2023-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(),
        ),
    ]
