# Generated by Django 4.2.2 on 2023-06-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviedate_remove_showtime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.moviedate'),
        ),
    ]
