# Generated by Django 4.2.2 on 2023-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
