# Generated by Django 4.2.2 on 2023-06-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_showtime_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='date',
            new_name='movie_date',
        ),
    ]
